"""initial_migration

Revision ID: f1d283b66100
Revises: 
Create Date: 2025-12-22 13:21:27.668469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d283b66100'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('deal_id', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('session_id', sa.String(), nullable=True))
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_foreign_key(None, 'audit_logs', 'deals', ['deal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('audit_logs', 'session_id')
    op.drop_column('audit_logs', 'deal_id')
    # ### end Alembic commands ###
